### ISSUE TITLE
UK's Call Allies to War Lingering Spam

### ISSUE THREAD

**Issue by rogerburks** [moretrim/ccHFM#63]
Although [addressed in previous versions of HFM](https://github.com/SighPie/HFM/pull/122), there are still occasions where the UK can spam a play-through with Wars of British Aggression to call a non-existent East India Company (`EIC`) to war, slowing down the game noticeably. This seems to occur when the East India Company no longer exists, such as in this case:

![image](https://user-images.githubusercontent.com/17787203/76982278-e1576280-68f8-11ea-81d8-e00b7e796b8e.png)

This decision is located in FlavourMod_Setup_CleanUp.txt, [`cleanup_eic`](https://github.com/moretrim/PFH/blob/700259d9c193b4c32d6bfd82970f79f22d7c65e5/PFH/decisions/FlavourMod_Setup_CleanUp.txt#L143-L223)

The `potential` is relatively simple, calling either the East India Company or the Rajputana Agency (`RAJ`) to war, therefore it occurs in the above case due to the existence of the Rajputana Agency.

The `allow` has 5 different clauses in an `OR` statement. Four of them require EIC to exist, and therefore the remaining one permits this decision to work:

https://github.com/moretrim/PFH/blob/700259d9c193b4c32d6bfd82970f79f22d7c65e5/PFH/decisions/FlavourMod_Setup_CleanUp.txt#L191-L202

Sure enough, the Rajputana Agency does not go to war:

![image](https://user-images.githubusercontent.com/17787203/76984161-b3bfe880-68fb-11ea-95a4-c11d045b2ddd.png)

Therefore the `allow` is always active until the UK stops being at war. The `effect` calls a custom casus belli that seems to be relatively simple:

https://github.com/moretrim/PFH/blob/700259d9c193b4c32d6bfd82970f79f22d7c65e5/PFH/decisions/FlavourMod_Setup_CleanUp.txt#L217-L222

https://github.com/moretrim/PFH/blob/700259d9c193b4c32d6bfd82970f79f22d7c65e5/PFH/common/cb_types.txt#L6395-L6428

Also it seems that none of the other UK puppets go to war either:

![image](https://user-images.githubusercontent.com/17787203/76985083-ef0ee700-68fc-11ea-99d6-10b22ed613af.png)

and this is occurring in a crisis war:

![image](https://user-images.githubusercontent.com/17787203/76985178-0f3ea600-68fd-11ea-884e-78934a17eff7.png)

The problem seems to be that nations cannot call allies to a crisis war before great wars are enabled, therefore the solution can be to require the UK to not be in a crisis war when using this:

![image](https://user-images.githubusercontent.com/17787203/76985621-be7b7d00-68fd-11ea-954e-a5058f173529.png)

**Comment by rogerburks** [comment]
Of course this is when I discover that there is no special indicator in normal modding terms for what is a crisis war (even though the game engine somehow knows). In order to get around this, I am testing a solution that requires great wars to be enabled after Revolution and Counterrevolution is researched by the great powers.

**Comment by rogerburks** [comment]
First pre-Revolution and Counterrevolution test worked:

![image](https://user-images.githubusercontent.com/17787203/77032771-9c681600-6962-11ea-8da8-67ee53f2d341.png)

**Comment by moretrim** [comment]
Since this was annoying to figure out I'm adding this note for posterity:

`involved_in_crisis = no` does not do what it suggests. Presumably (though this has not been tested) its result is only meaningful while there *is* a crisis going on. Here is what it looks like when there is no crisis:

![debug decision tooltip without a crisis going on](https://user-images.githubusercontent.com/49937701/78508034-234f2800-7784-11ea-998d-cb3608604156.png)

The UK as well as player country the Khanate of Kokand are both simultaneously *not* involved in a crisis and *not* **not** involved in a crisis. When it comes to negating `involved_in_crisis = yes` you have to do it the long way around, as can be seen in other parts of the mod:

https://github.com/moretrim/PFH/blob/dc856f83a37f545190437e73145eb7a0968799f9/PFH/events/CBGeneration.txt#L9
